name: tekartik_app_element
version: 0.0.1
environment:
  sdk: ">=1.2.0 <2.0.0"
dependencies:
  polymer_elements: ">=1.0.0-rc"
  polymer: ">=1.0.0-rc"
  web_components: any
  reflectable: any
  markdown: any
  pool: any
  analyzer: "<=0.27.1"
  idb_shim: ">=1.2.1"
  tekartik_idb_provider:
    git: git://github.com/alextekartik/tekartik_idb_provider.dart
  tekartik_gapi_mock:
    git: https://bitbucket.org/alextk/gapi_mock.dart
  tekartik_google_jsapi:
    git: git://github.com/alextekartik/google-jsapi.dart
  tekartik_utils:
    git: git://github.com/alextekartik/tekartik_utils.dart
  tekartik_html:
    git: git://github.com/alextekartik/tekartik_html.dart
  yacht:
    git: git://github.com/tekartik/yacht.dart
  dart_to_js_script_rewriter: any

transformers:
# Needed for Html registration
- polymer:
    entry_points:
    - example/gapi_flow_example.html
    - example/element_utils_example.html
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
- dart_to_js_script_rewriter
# - yacht
dev_dependencies:
  test: any
  dev_test: any
  tekartik_test:
    git: git://github.com/alextekartik/tekartik_test.dart

dependency_overrides:
  # polymer: ^1.0.0-rc.6
  # polymer_elements: ^1.0.0-rc.3
#  tekartik_idb_provider:
#    path: /media/ssd/devx/git/tekartik_idb_provider.dart
#  polymer:
#    git:
#      ref: 1.0.0-rc.2
#      url: https://github.com/dart-lang/polymer-dart.git
#  polymer_interop:
#    git:
#      ref: 0.2.0-rc1
#      url: https://github.com/dart-lang/polymer_interop.git
#  reflectable: 0.3.0
#  tekartik_google_jsapi:
#    path: /media/ssd/devx/git/google-jsapi.dart
#  idb_shim:
#    git: https://github.com/alextekartik/idb_shim.dart


